#!/usr/bin/env python3
"""CLI for the H2 Adsorption Storage Simulator engine.

  python engine/run.py                          # spec defaults -> out/
  python engine/run.py --q-st 6 --unit wt_pct
  python engine/run.py --basis pure_framework   # Section 4.1 read literally
  python engine/run.py --emit-web-constants     # refresh the browser app's model data
  python engine/run.py --validate results.csv   # independent 77 K validation
"""
from __future__ import annotations

import argparse
import csv
import json
import sys
from dataclasses import asdict
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent))

import model as M
import deliverables as D

ROOT = Path(__file__).resolve().parent.parent


def emit_web_constants(path: Path, opts: M.Options) -> Path:
    """Single source of truth for the browser app's fitted parameters."""
    payload = {
        "generated_by": "engine/run.py --emit-web-constants",
        "constants": {"R": M.R, "M_H2": M.M_H2, "T_BENCH": M.T_BENCH,
                      "T_PROD": M.T_PROD, "PRESSURES": list(M.PRESSURES)},
        "fits": {
            mdl: {z: asdict(M.fit_benchmark(z, mdl)) for z in ("13X", "5A")}
            for mdl in M.ISOTHERM_MODELS
        },
        "models": {k: {"label": v["label"], "params": list(v["params"]), "note": v["note"]}
                   for k, v in M.ISOTHERM_MODELS.items()},
        "materials": {k: asdict(v) for k, v in M.MATERIALS.items()},
        "nano_ac": M.NANO_AC,
        "configs": [{"run": c.run, "zeolite": c.zeolite, "form": c.form,
                     "composite": c.composite, "priority": c.priority, "label": c.label}
                    for c in M.CONFIGS],
        "factors": {"powder": M.POWDER_ENHANCEMENT, "composite": M.COMPOSITE_ENHANCEMENT,
                    "zeolite_fraction": M.ZEOLITE_FRACTION,
                    "nano_ac_fraction": M.NANO_AC_FRACTION,
                    "bed_loading_g": M.BED_LOADING_G},
        "benchmark": {"source": "Langmi et al. (2003) J. Alloys Compd. 356-357, 710-715",
                      "tolerance": M.VALIDATION_TOLERANCE, "data": M.LANGMI_77K},
        "vessel": {**M.vessel_geometry(), "void_fraction": M.VOID_FRACTION},
        "notes": {"excess_vs_absolute": M.EXCESS_NOTE},
        "defaults": asdict(opts),
    }
    path.parent.mkdir(parents=True, exist_ok=True)
    body = json.dumps(payload, indent=2)
    path.write_text(body)
    # Also emit a plain-JS form so the browser app opens from file:// without a
    # server -- fetch() of a local .json is blocked by most browsers' CORS rules.
    path.with_suffix(".js").write_text(
        "// Generated by engine/run.py --emit-web-constants. Do not edit by hand.\n"
        "window.MODEL_CONSTANTS = " + body + ";\n")
    return path


def load_external(csv_path: Path) -> dict:
    """CSV: zeolite,pressure_bar,wt_pct  — externally produced 77 K results."""
    out: dict = {}
    with open(csv_path, newline="") as fh:
        for row in csv.DictReader(fh):
            out.setdefault(row["zeolite"].strip(), []).append(float(row["wt_pct"]))
    return out


def main(argv=None):
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--q-st", type=float, default=4.0, help="isosteric heat, kJ/mol")
    ap.add_argument("--temperature", type=float, default=M.T_PROD, help="kelvin")
    ap.add_argument("--model", choices=list(M.ISOTHERM_MODELS), default="sips")
    ap.add_argument("--basis", choices=["literature", "pure_framework"], default="literature")
    ap.add_argument("--approach", choices=["A", "B"], default="B", help="composite method")
    ap.add_argument("--unit", choices=["mg_per_g", "wt_pct"], default="mg_per_g")
    ap.add_argument("--out", type=Path, default=ROOT / "out")
    ap.add_argument("--emit-web-constants", action="store_true")
    ap.add_argument("--validate", type=Path, metavar="CSV",
                    help="independent 77 K validation of external results")
    a = ap.parse_args(argv)

    opts = M.Options(q_st=a.q_st, temperature=a.temperature, isotherm_model=a.model,
                     basis=a.basis, composite_approach=a.approach)

    if a.emit_web_constants:
        p = emit_web_constants(ROOT / "web" / "model-constants.json", opts)
        print(f"web constants -> {p.relative_to(ROOT)}")
        if not a.validate:
            return 0

    if a.validate:
        res = M.validate_external(load_external(a.validate))
        print(f"\nIndependent validation at 77 K — {res['passed']}/{res['total']} within ±15%")
        print(f"{'Zeolite':<9}{'P (bar)':>9}{'Result':>10}{'Target':>10}{'Error':>10}  Verdict")
        for r in res["rows"]:
            print(f"{r['zeolite']:<9}{r['pressure_bar']:>9.0f}{r['predicted_wt_pct']:>10.4f}"
                  f"{r['target_wt_pct']:>10.2f}{r['error_pct']:>9.1f}%  "
                  f"{'PASS' if r['pass'] else 'FAIL'}")
        for z, v in res["per_zeolite"].items():
            print(f"  {z}: {v['failures']} failure(s) — Section 6 verdict: "
                  f"{'PASS' if v['section6_pass'] else 'FAIL'}")
        print(f"  Section 10 checklist (10/10 required): "
              f"{'PASS' if res['all_pass'] else 'FAIL'}")
        return 0 if res["all_pass"] else 1

    res = D.export_all(opts, a.out, a.unit)
    key = "mg_per_g" if a.unit == "mg_per_g" else "wt_pct"
    unit_label = "mg/g" if a.unit == "mg_per_g" else "wt%"

    print(f"\nH₂ Adsorption Simulator — {opts.temperature:.0f} K, q_st = {opts.q_st:g} kJ/mol, "
          f"{M.ISOTHERM_MODELS[opts.isotherm_model]['label']}, basis={opts.basis}, "
          f"approach {opts.composite_approach}\n")
    print(f"{'Run':<4}{'Configuration':<26}" + "".join(f"{p:>10.0f}" for p in opts.pressures))
    print(f"{'':<30}" + "".join(f"{unit_label:>10}" for _ in opts.pressures))
    print("-" * (30 + 10 * len(opts.pressures)))
    for r in res["matrix"]:
        print(f"{r['run']:<4}{r['label']:<26}" + "".join(f"{v:>10.4f}" for v in r[key]))

    best = max(res["matrix"], key=lambda r: r[key][-1])
    print(f"\nBest: Run {best['run']} — {best['label']} "
          f"({best[key][-1]:.4f} {unit_label} at {opts.pressures[-1]:g} bar)")
    print(f"Benchmark fit check: {res['check']['passed']}/{res['check']['total']} "
          f"within ±15% (fit quality, not independent validation)")
    print(f"q_st sensitivity: {res['sens']['spread_factor']:.0f}× spread across 4–8 kJ/mol")

    sb = M.storage_balance(res["matrix"][5]["wt_pct"][-1], opts.pressures[-1], opts.temperature)
    print(f"Storage balance at {opts.pressures[-1]:g} bar: {sb['adsorbed_g']:.3f} g adsorbed vs "
          f"{sb['free_gas_g']:.3f} g free gas ({sb['adsorbed_fraction']*100:.0f}% by adsorption)")

    print("\nDeliverables:")
    for k in ("xlsx", "docx", "methodology", "isotherms", "sensitivity", "validation", "raw"):
        print(f"  {k:<12} {Path(res[k]).relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
